# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wind.ui'
#
# Created: Thu Apr 19 14:10:04 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(577, 392)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(390, 139))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 391, 101))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(381, 101))
        self.frame.setStyleSheet(_fromUtf8("background-color: rgb(234, 234, 234)"))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.Play = QtGui.QPushButton(self.frame)
        self.Play.setGeometry(QtCore.QRect(50, 40, 41, 41))
        self.Play.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("res/icons/gtk-media-play-ltr.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Play.setIcon(icon)
        self.Play.setIconSize(QtCore.QSize(24, 24))
        self.Play.setObjectName(_fromUtf8("Play"))
        self.Previous = QtGui.QPushButton(self.frame)
        self.Previous.setGeometry(QtCore.QRect(10, 40, 41, 41))
        self.Previous.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("res/icons/player_start.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Previous.setIcon(icon1)
        self.Previous.setIconSize(QtCore.QSize(24, 24))
        self.Previous.setObjectName(_fromUtf8("Previous"))
        self.Pause = QtGui.QPushButton(self.frame)
        self.Pause.setGeometry(QtCore.QRect(90, 40, 41, 41))
        self.Pause.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("res/icons/gtk-media-pause.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Pause.setIcon(icon2)
        self.Pause.setIconSize(QtCore.QSize(24, 24))
        self.Pause.setObjectName(_fromUtf8("Pause"))
        self.songprg_num = QtGui.QLabel(self.frame)
        self.songprg_num.setGeometry(QtCore.QRect(250, 50, 91, 20))
        self.songprg_num.setText(_fromUtf8(""))
        self.songprg_num.setObjectName(_fromUtf8("songprg_num"))
        self.songprg = QtGui.QSlider(self.frame)
        self.songprg.setGeometry(QtCore.QRect(10, 20, 371, 21))
        self.songprg.setTracking(True)
        self.songprg.setOrientation(QtCore.Qt.Horizontal)
        self.songprg.setObjectName(_fromUtf8("songprg"))
        self.Next = QtGui.QPushButton(self.frame)
        self.Next.setGeometry(QtCore.QRect(170, 40, 41, 41))
        self.Next.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("res/icons/player_end.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Next.setIcon(icon3)
        self.Next.setIconSize(QtCore.QSize(24, 24))
        self.Next.setObjectName(_fromUtf8("Next"))
        self.Stop = QtGui.QPushButton(self.frame)
        self.Stop.setGeometry(QtCore.QRect(130, 40, 41, 41))
        self.Stop.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("res/icons/gtk-media-stop.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Stop.setIcon(icon4)
        self.Stop.setIconSize(QtCore.QSize(24, 24))
        self.Stop.setObjectName(_fromUtf8("Stop"))
        self.songlb = QtGui.QLabel(self.frame)
        self.songlb.setGeometry(QtCore.QRect(10, -1, 371, 21))
        self.songlb.setStyleSheet(_fromUtf8("background-color: rgb(243, 243, 243);"))
        self.songlb.setFrameShape(QtGui.QFrame.StyledPanel)
        self.songlb.setFrameShadow(QtGui.QFrame.Sunken)
        self.songlb.setText(_fromUtf8(""))
        self.songlb.setObjectName(_fromUtf8("songlb"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 577, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionUpdate = QtGui.QAction(MainWindow)
        self.actionUpdate.setObjectName(_fromUtf8("actionUpdate"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menuFile.addAction(self.actionUpdate)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.songprg, self.Play)
        MainWindow.setTabOrder(self.Play, self.Pause)
        MainWindow.setTabOrder(self.Pause, self.Stop)
        MainWindow.setTabOrder(self.Stop, self.Previous)
        MainWindow.setTabOrder(self.Previous, self.Next)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdate.setText(QtGui.QApplication.translate("MainWindow", "Update DB", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdate.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+U", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))

