# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wind.ui'
#
# Created: Fri May  4 12:44:28 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(401, 396)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(390, 139))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("res/icons/go-home.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.songsTabContainer = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.songsTabContainer.sizePolicy().hasHeightForWidth())
        self.songsTabContainer.setSizePolicy(sizePolicy)
        self.songsTabContainer.setMinimumSize(QtCore.QSize(200, 0))
        self.songsTabContainer.setTabShape(QtGui.QTabWidget.Rounded)
        self.songsTabContainer.setMovable(True)
        self.songsTabContainer.setObjectName(_fromUtf8("songsTabContainer"))
        self.tabPlaylist = QtGui.QWidget()
        self.tabPlaylist.setObjectName(_fromUtf8("tabPlaylist"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabPlaylist)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.playlist = QtGui.QListWidget(self.tabPlaylist)
        self.playlist.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playlist.sizePolicy().hasHeightForWidth())
        self.playlist.setSizePolicy(sizePolicy)
        self.playlist.setMinimumSize(QtCore.QSize(370, 151))
        self.playlist.setAcceptDrops(False)
        self.playlist.setFrameShadow(QtGui.QFrame.Raised)
        self.playlist.setAlternatingRowColors(True)
        self.playlist.setObjectName(_fromUtf8("playlist"))
        self.gridLayout_2.addWidget(self.playlist, 0, 0, 1, 1)
        self.songsTabContainer.addTab(self.tabPlaylist, _fromUtf8(""))
        self.tabLibrary = QtGui.QWidget()
        self.tabLibrary.setObjectName(_fromUtf8("tabLibrary"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabLibrary)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.library = QtGui.QTreeWidget(self.tabLibrary)
        self.library.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.library.sizePolicy().hasHeightForWidth())
        self.library.setSizePolicy(sizePolicy)
        self.library.setMinimumSize(QtCore.QSize(370, 151))
        self.library.setAcceptDrops(True)
        self.library.setFrameShadow(QtGui.QFrame.Raised)
        self.library.setAlternatingRowColors(True)
        self.library.setHeaderHidden(True)
        self.library.setObjectName(_fromUtf8("library"))
        self.gridLayout_3.addWidget(self.library, 0, 0, 1, 1)
        self.songsTabContainer.addTab(self.tabLibrary, _fromUtf8(""))
        self.tabSearch = QtGui.QWidget()
        self.tabSearch.setObjectName(_fromUtf8("tabSearch"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tabSearch)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.search = QtGui.QListWidget(self.tabSearch)
        self.search.setFrameShadow(QtGui.QFrame.Raised)
        self.search.setAlternatingRowColors(True)
        self.search.setObjectName(_fromUtf8("search"))
        self.gridLayout_6.addWidget(self.search, 1, 0, 1, 1)
        self.searchEdit = QtGui.QLineEdit(self.tabSearch)
        self.searchEdit.setObjectName(_fromUtf8("searchEdit"))
        self.gridLayout_6.addWidget(self.searchEdit, 0, 0, 1, 1)
        self.songsTabContainer.addTab(self.tabSearch, _fromUtf8(""))
        self.gridLayout.addWidget(self.songsTabContainer, 2, 0, 1, 1)
        self.frame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(381, 101))
        self.frame.setStyleSheet(_fromUtf8("background-color: rgb(234, 234, 234)"))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.play = QtGui.QPushButton(self.frame)
        self.play.setGeometry(QtCore.QRect(50, 40, 41, 41))
        self.play.setStyleSheet(_fromUtf8("border-color: rgb(38, 38, 38);"))
        self.play.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("res/icons/gtk-media-play-ltr.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play.setIcon(icon1)
        self.play.setIconSize(QtCore.QSize(24, 24))
        self.play.setFlat(True)
        self.play.setObjectName(_fromUtf8("play"))
        self.previous = QtGui.QPushButton(self.frame)
        self.previous.setGeometry(QtCore.QRect(10, 40, 41, 41))
        self.previous.setStyleSheet(_fromUtf8("border-color: rgb(38, 38, 38);"))
        self.previous.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("res/icons/player_start.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previous.setIcon(icon2)
        self.previous.setIconSize(QtCore.QSize(24, 24))
        self.previous.setFlat(True)
        self.previous.setObjectName(_fromUtf8("previous"))
        self.pause = QtGui.QPushButton(self.frame)
        self.pause.setGeometry(QtCore.QRect(90, 40, 41, 41))
        self.pause.setStyleSheet(_fromUtf8("border-color: rgb(38, 38, 38);"))
        self.pause.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("res/icons/gtk-media-pause.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pause.setIcon(icon3)
        self.pause.setIconSize(QtCore.QSize(24, 24))
        self.pause.setFlat(True)
        self.pause.setObjectName(_fromUtf8("pause"))
        self.songprg_num = QtGui.QLabel(self.frame)
        self.songprg_num.setGeometry(QtCore.QRect(250, 50, 121, 20))
        self.songprg_num.setText(_fromUtf8(""))
        self.songprg_num.setObjectName(_fromUtf8("songprg_num"))
        self.songprg = QtGui.QSlider(self.frame)
        self.songprg.setGeometry(QtCore.QRect(10, 20, 361, 21))
        self.songprg.setTracking(True)
        self.songprg.setOrientation(QtCore.Qt.Horizontal)
        self.songprg.setObjectName(_fromUtf8("songprg"))
        self.next = QtGui.QPushButton(self.frame)
        self.next.setGeometry(QtCore.QRect(170, 40, 41, 41))
        self.next.setStyleSheet(_fromUtf8("border-color: rgb(38, 38, 38);"))
        self.next.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("res/icons/player_end.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next.setIcon(icon4)
        self.next.setIconSize(QtCore.QSize(24, 24))
        self.next.setFlat(True)
        self.next.setObjectName(_fromUtf8("next"))
        self.stop = QtGui.QPushButton(self.frame)
        self.stop.setGeometry(QtCore.QRect(130, 40, 41, 41))
        self.stop.setStyleSheet(_fromUtf8("border-color: rgb(38, 38, 38);"))
        self.stop.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("res/icons/gtk-media-stop.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop.setIcon(icon5)
        self.stop.setIconSize(QtCore.QSize(24, 24))
        self.stop.setFlat(True)
        self.stop.setObjectName(_fromUtf8("stop"))
        self.songlb = QtGui.QLabel(self.frame)
        self.songlb.setGeometry(QtCore.QRect(10, 0, 361, 21))
        self.songlb.setStyleSheet(_fromUtf8("background-color: rgb(243, 243, 243);"))
        self.songlb.setFrameShape(QtGui.QFrame.StyledPanel)
        self.songlb.setFrameShadow(QtGui.QFrame.Sunken)
        self.songlb.setText(_fromUtf8(""))
        self.songlb.setObjectName(_fromUtf8("songlb"))
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 401, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionUpdateDB = QtGui.QAction(MainWindow)
        self.actionUpdateDB.setObjectName(_fromUtf8("actionUpdateDB"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionViewPlaylist = QtGui.QAction(MainWindow)
        self.actionViewPlaylist.setObjectName(_fromUtf8("actionViewPlaylist"))
        self.actionViewLibrary = QtGui.QAction(MainWindow)
        self.actionViewLibrary.setObjectName(_fromUtf8("actionViewLibrary"))
        self.actionViewCurrentSong = QtGui.QAction(MainWindow)
        self.actionViewCurrentSong.setObjectName(_fromUtf8("actionViewCurrentSong"))
        self.actionRepeatAll = QtGui.QAction(MainWindow)
        self.actionRepeatAll.setCheckable(True)
        self.actionRepeatAll.setObjectName(_fromUtf8("actionRepeatAll"))
        self.actionRandom = QtGui.QAction(MainWindow)
        self.actionRandom.setCheckable(True)
        self.actionRandom.setObjectName(_fromUtf8("actionRandom"))
        self.actionPlay = QtGui.QAction(MainWindow)
        self.actionPlay.setObjectName(_fromUtf8("actionPlay"))
        self.actionPause = QtGui.QAction(MainWindow)
        self.actionPause.setObjectName(_fromUtf8("actionPause"))
        self.actionStop = QtGui.QAction(MainWindow)
        self.actionStop.setObjectName(_fromUtf8("actionStop"))
        self.actionNext = QtGui.QAction(MainWindow)
        self.actionNext.setObjectName(_fromUtf8("actionNext"))
        self.actionPrevious = QtGui.QAction(MainWindow)
        self.actionPrevious.setObjectName(_fromUtf8("actionPrevious"))
        self.actionAdd = QtGui.QAction(MainWindow)
        self.actionAdd.setObjectName(_fromUtf8("actionAdd"))
        self.actionRemove = QtGui.QAction(MainWindow)
        self.actionRemove.setObjectName(_fromUtf8("actionRemove"))
        self.actionViewSearch = QtGui.QAction(MainWindow)
        self.actionViewSearch.setObjectName(_fromUtf8("actionViewSearch"))
        self.actionClear = QtGui.QAction(MainWindow)
        self.actionClear.setObjectName(_fromUtf8("actionClear"))
        self.menuFile.addAction(self.actionUpdateDB)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuView.addAction(self.actionViewPlaylist)
        self.menuView.addAction(self.actionViewLibrary)
        self.menuView.addAction(self.actionViewSearch)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionViewCurrentSong)
        self.menuEdit.addAction(self.actionPlay)
        self.menuEdit.addAction(self.actionPause)
        self.menuEdit.addAction(self.actionStop)
        self.menuEdit.addAction(self.actionNext)
        self.menuEdit.addAction(self.actionPrevious)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionRepeatAll)
        self.menuEdit.addAction(self.actionRandom)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionAdd)
        self.menuEdit.addAction(self.actionRemove)
        self.menuEdit.addAction(self.actionClear)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.songsTabContainer.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.songprg, self.previous)
        MainWindow.setTabOrder(self.previous, self.play)
        MainWindow.setTabOrder(self.play, self.pause)
        MainWindow.setTabOrder(self.pause, self.stop)
        MainWindow.setTabOrder(self.stop, self.next)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "musicroxx", None, QtGui.QApplication.UnicodeUTF8))
        self.playlist.setSortingEnabled(False)
        self.songsTabContainer.setTabText(self.songsTabContainer.indexOf(self.tabPlaylist), QtGui.QApplication.translate("MainWindow", "Playlist", None, QtGui.QApplication.UnicodeUTF8))
        self.library.setSortingEnabled(True)
        self.library.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Filename", None, QtGui.QApplication.UnicodeUTF8))
        self.songsTabContainer.setTabText(self.songsTabContainer.indexOf(self.tabLibrary), QtGui.QApplication.translate("MainWindow", "Library", None, QtGui.QApplication.UnicodeUTF8))
        self.searchEdit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.songsTabContainer.setTabText(self.songsTabContainer.indexOf(self.tabSearch), QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdateDB.setText(QtGui.QApplication.translate("MainWindow", "Update DB", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdateDB.setShortcut(QtGui.QApplication.translate("MainWindow", "U", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionViewPlaylist.setText(QtGui.QApplication.translate("MainWindow", "Playlist", None, QtGui.QApplication.UnicodeUTF8))
        self.actionViewPlaylist.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionViewLibrary.setText(QtGui.QApplication.translate("MainWindow", "Library", None, QtGui.QApplication.UnicodeUTF8))
        self.actionViewLibrary.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+L", None, QtGui.QApplication.UnicodeUTF8))
        self.actionViewCurrentSong.setText(QtGui.QApplication.translate("MainWindow", "Current Song", None, QtGui.QApplication.UnicodeUTF8))
        self.actionViewCurrentSong.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+U", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRepeatAll.setText(QtGui.QApplication.translate("MainWindow", "Repeat", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRepeatAll.setShortcut(QtGui.QApplication.translate("MainWindow", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRandom.setText(QtGui.QApplication.translate("MainWindow", "Random", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRandom.setShortcut(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay.setText(QtGui.QApplication.translate("MainWindow", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay.setShortcut(QtGui.QApplication.translate("MainWindow", "P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPause.setText(QtGui.QApplication.translate("MainWindow", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPause.setShortcut(QtGui.QApplication.translate("MainWindow", "Shift+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop.setShortcut(QtGui.QApplication.translate("MainWindow", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext.setText(QtGui.QApplication.translate("MainWindow", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext.setShortcut(QtGui.QApplication.translate("MainWindow", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrevious.setText(QtGui.QApplication.translate("MainWindow", "Previous", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrevious.setShortcut(QtGui.QApplication.translate("MainWindow", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd.setShortcut(QtGui.QApplication.translate("MainWindow", "Space", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove.setShortcut(QtGui.QApplication.translate("MainWindow", "Backspace", None, QtGui.QApplication.UnicodeUTF8))
        self.actionViewSearch.setText(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.actionViewSearch.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear.setShortcut(QtGui.QApplication.translate("MainWindow", "C", None, QtGui.QApplication.UnicodeUTF8))

