# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wind2.ui'
#
# Created: Wed Apr 18 17:06:14 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(577, 392)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(403, 160))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 411, 351))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.frame = QtGui.QFrame(self.frame_2)
        self.frame.setGeometry(QtCore.QRect(10, 30, 391, 101))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(381, 101))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.Play = QtGui.QPushButton(self.frame)
        self.Play.setGeometry(QtCore.QRect(10, 40, 75, 26))
        self.Play.setObjectName(_fromUtf8("Play"))
        self.Previous = QtGui.QPushButton(self.frame)
        self.Previous.setGeometry(QtCore.QRect(30, 70, 75, 26))
        self.Previous.setObjectName(_fromUtf8("Previous"))
        self.Pause = QtGui.QPushButton(self.frame)
        self.Pause.setGeometry(QtCore.QRect(90, 40, 75, 26))
        self.Pause.setObjectName(_fromUtf8("Pause"))
        self.songprg_num = QtGui.QLabel(self.frame)
        self.songprg_num.setGeometry(QtCore.QRect(290, 10, 91, 20))
        self.songprg_num.setText(_fromUtf8(""))
        self.songprg_num.setObjectName(_fromUtf8("songprg_num"))
        self.songprg = QtGui.QSlider(self.frame)
        self.songprg.setGeometry(QtCore.QRect(10, 10, 271, 21))
        self.songprg.setTracking(True)
        self.songprg.setOrientation(QtCore.Qt.Horizontal)
        self.songprg.setObjectName(_fromUtf8("songprg"))
        self.Quit = QtGui.QPushButton(self.frame)
        self.Quit.setGeometry(QtCore.QRect(190, 70, 75, 26))
        self.Quit.setObjectName(_fromUtf8("Quit"))
        self.Next = QtGui.QPushButton(self.frame)
        self.Next.setGeometry(QtCore.QRect(110, 70, 75, 26))
        self.Next.setObjectName(_fromUtf8("Next"))
        self.Stop = QtGui.QPushButton(self.frame)
        self.Stop.setGeometry(QtCore.QRect(170, 40, 75, 26))
        self.Stop.setObjectName(_fromUtf8("Stop"))
        self.songlb = QtGui.QLabel(self.frame_2)
        self.songlb.setGeometry(QtCore.QRect(20, 10, 371, 20))
        self.songlb.setText(_fromUtf8(""))
        self.songlb.setObjectName(_fromUtf8("songlb"))
        self.playlist = QtGui.QListWidget(self.frame_2)
        self.playlist.setGeometry(QtCore.QRect(15, 140, 381, 192))
        self.playlist.setFrameShadow(QtGui.QFrame.Raised)
        self.playlist.setObjectName(_fromUtf8("playlist"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 577, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionUpdate = QtGui.QAction(MainWindow)
        self.actionUpdate.setObjectName(_fromUtf8("actionUpdate"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menuFile.addAction(self.actionUpdate)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QObject.connect(self.Quit, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.songprg, self.Play)
        MainWindow.setTabOrder(self.Play, self.Pause)
        MainWindow.setTabOrder(self.Pause, self.Stop)
        MainWindow.setTabOrder(self.Stop, self.Previous)
        MainWindow.setTabOrder(self.Previous, self.Next)
        MainWindow.setTabOrder(self.Next, self.Quit)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.Play.setText(QtGui.QApplication.translate("MainWindow", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.Previous.setText(QtGui.QApplication.translate("MainWindow", "Previous", None, QtGui.QApplication.UnicodeUTF8))
        self.Pause.setText(QtGui.QApplication.translate("MainWindow", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.Quit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.Next.setText(QtGui.QApplication.translate("MainWindow", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.Stop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdate.setText(QtGui.QApplication.translate("MainWindow", "Update DB", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdate.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+U", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))

